# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "cookbooks/example/Berksfile"

  config.vm.box = "debian/stretch64"

  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "example"
  end
end
