# -*- mode: ruby -*-
# vi: set ft=ruby :

# requires vagrant-winrm, vagrant-triggers plugin

# change this to match the interface you want to use
BRIDGE_INTERFACE = 'en0: WLAN (AirPort)'
# adapt number of students VMs
STUDENTS = 2
# box that is used for all VMs
BOX = "opentable/win-2012r2-standard-amd64-nocm"

Vagrant.configure(2) do |config|

  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "cookbooks/windows-example/Berksfile"

  (1..STUDENTS).each do |i|
    config.vm.define "student#{i}".to_sym do |student|
      student.vm.box = BOX

      config.vm.network :forwarded_port, guest: 3389, host: 2200, auto_correct: true

      student.vm.provider 'virtualbox' do |vb|
        vb.customize ['modifyvm', :id, '--memory', '1024']
      end

      config.vm.provision "chef_solo" do |chef|
        chef.cookbooks_path = "cookbooks"
        chef.add_recipe "windows-example"
      end

    end
  end

  config.trigger.after :up do
    `rm -f ports.txt`
    (1..STUDENTS).each do |i|
      `echo student#{i} >> ports.txt`
      `vagrant port student#{i} | grep 3389 >> ports.txt`
    end
  end

  config.trigger.after :destroy do
    run "rm -f ports.txt"
  end

end
