name 'windows-example'
maintainer 'Sebastian Sucker'
maintainer_email 'sebastian@endocode.com'
license 'MIT'
description 'example windows cookbook'
long_description 'shows basic chef usage for windows plattform'
version '0.0.1'

depends 'windows'
depends 'chocolatey'
