# -*- mode: ruby -*-
# vi: set ft=ruby :

# requires vagrant-triggers plugin

# Download ChefDK to share it with all VMs
unless File.file?('chefdk_0.18.30-1_amd64.deb')
  `wget https://packages.chef.io/stable/ubuntu/12.04/chefdk_0.18.30-1_amd64.deb`
end

# change this to match the interface you want to use
BRIDGE_INTERFACE = 'en0: WLAN (AirPort)'
# adapt number of students VMs
STUDENTS = 5
# box that is used for all VMs
BOX = "ubuntu/trusty64"

Vagrant.configure("2") do |config|

  (1..STUDENTS).each do |i|
    config.vm.define "student#{i}".to_sym do |student|
      student.vm.box = BOX
      student.vm.network :public_network, bridge: BRIDGE_INTERFACE, type: "dhcp"
      student.vm.provider 'virtualbox' do |vb|
        vb.customize ['modifyvm', :id, '--memory', '512']
      end
      student.vm.provision "shell", inline: "dpkg -i /vagrant/chefdk_0.18.30-1_amd64.deb"
      student.vm.provision "shell", inline: "ifconfig eth1 | grep 'inet addr' >> /vagrant/ips.txt"

    end
  end

  config.trigger.after :destroy do
    run "rm ips.txt"
  end

end
