# -*- mode: ruby -*-
# vi: set ft=ruby :

# requires vagrant-triggers plugin

# adapt number of students VMs
STUDENTS = 12

# Download ChefDK to share it with all VMs
unless File.file?('chefdk_0.18.30-1_amd64.deb')
  `wget https://packages.chef.io/stable/ubuntu/12.04/chefdk_0.18.30-1_amd64.deb`
end

Vagrant.configure("2") do |config|

  (1..STUDENTS).each do |i|
    config.vm.define "student#{i}".to_sym do |student|
      student.vm.box = "ubuntu/trusty64"
      student.vm.provider 'virtualbox' do |vb|
        vb.customize ['modifyvm', :id, '--memory', '512']
      end
      student.vm.provision "shell", inline: "dpkg -i /vagrant/chefdk_0.18.30-1_amd64.deb"
    end
  end

  config.trigger.after :up do
    `rm -f ports.txt`
    (1..STUDENTS).each do |i|
      `echo student#{i} >> ports.txt`
      `vagrant port student#{i} | grep 22 >> ports.txt`
    end
  end

  config.trigger.after :destroy do
    run "rm -f ports.txt"
  end

end
